### ISSUE TITLE
Selected product

### ISSUE THREAD

**Issue by Abdelrahman059** [GSG-FC03/foodk-app#17]
**Create the selected product contains the chosen item like a dish or drink**#9
This page contains :
- [x] Listing Product Info Whether Drink/food
- [x] Three types of info (Quantities, Ingredients, name of the selected Item, and Instructions)
- [x] Background

**UI Design**
![image](https://user-images.githubusercontent.com/82518895/128310908-0ff06263-e985-4ca0-a8dc-2ff295ddda8a.png)

**Comment by salsabeelomar** [comment]
it takes  more than 3 hours I face some problem intake one item and when I click on IMG in drink it displays for second drink IMG  then display IMG from food page that I was a click in it
